apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpjeApNVE01TURKYUZ3MDBNekF4TWpjeE1UTTVNREphTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUi8vNG1GbDR1TzltUUdlYlFrWFJUdjAvUzAwK0RMVlIxbU04NHloR2dzcFZUTUg0NQpjVTEzcTFOM3c3cHI3cnJJd3pmQWpmQUNheHltcDgwZStaOVIwRjNIejBIbEpOeTl1SFVGRlhtT3Q5WGtUcGNDCjR6MGN4V3dZVzVSeEhYNiszeFNpY3FmT1BVYlppZFJzVURNY3A0dVJ6WTVhL0R6dDFmSStZZmUyYW9Ca3lscEQKZGhMY09vNlpYYlgwNWdlellrSUs2Rm5jZ2x0amZDZXBPamF5dTlwdlo2aFNxc1AxNHQ5NUcvelpCd3dXeWhvQwpPMUZ2UFdROEozc0puN2ZKVzlucEJoRThmcXNyUUNXTTF5cGgwWGJvM3p2NVZXaXRKYVlzaVJtL241RkdiVTJICkVCK3NlOC95dnJoYldMMjgvcEwwU284VUNTK3FkL0RBT2RuWkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNURG85WXpNdTlCMXNtQURhUgpvSFVKSHE1aVFEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvMUZBTXZ6Y3kzTkZJdVpjWFZqYzJYV01Id2IxCjgvYmZKOTRtbGRJUE5RRkNhd0lnVjdLaHNzMXgvZEtQR3QyaDk5Y2o1OFFacHNxWk5EMGl0YmtDTUt5dlpwYSsKVGY1SmFnUHZ2TTFzNm8ra2lQS0VhNE9xS09ua1RvV0lUaDZ2K09zRjFWOTNDZldHeDkzNkJwaHpDS1cyKzdoWAppWFEvQkV1Vkl6SFBqOEEvWWYwZnZUR3VRS0tTTlp2N2JjQ3VybTVPUHlRV1ZjSnUwS2dzZEwrbVZLVGVJTEwvCjFXeVNneHVKQTN3dkFWZzB1aENvZHFHeWNaNGNZOTl1YXlOWE1mamFFY1pnZ3I3YmhkdWxoNXJLN25ycXB2VnUKWENlNlFVdFZsbVMzejNwOXdGQ3ZWV2ZJbmRsaEpWWFpmVDBWQ1NPZGRYVThOQnNJUjBabnNyK1A5Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://67053e78-b3cd-4f81-b98d-f5903fe1bce2.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_0dcdb940f2e9727ff69095609e4f8b75808e3fd6ca78fea6271cfdd305cb5768